### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: com/google/api/client/json/jackson2/JacksonFactory

### ISSUE THREAD

**Issue by tonyshkurenko** [GoogleCloudPlatform/artifact-registry-maven-tools#44]
Hi, I've got an exception, after updating AGP to 4.2.1, Gradle 6.7.1, artifactory plugin: 2.1.1

```
Caused by: java.lang.NoClassDefFoundError: com/google/api/client/json/jackson2/JacksonFactory
        at com.google.cloud.artifactregistry.auth.DefaultCredentialProvider.getCredential(DefaultCredentialProvider.java:49)
        at com.google.cloud.artifactregistry.gradle.plugin.ArtifactRegistryGradlePlugin.apply(ArtifactRegistryGradlePlugin.java:84)

```

**Comment by tonyshkurenko** [comment]
I've found when it happens:

When I update https://github.com/Triple-T/gradle-play-publisher from 3.3.0 to 3.4.0, but error is related to artifactory

**Comment by Gridasov** [comment]
The gradle/maven plugins depend on com.google.http-client:google-http-client-jackson2, but we get it only as a transitive dependency from google-auth-library-oauth2-http.
Could  you share your pom.xml?

**Comment by tonyshkurenko** [comment]
May it be somehow related to: https://github.com/Triple-T/gradle-play-publisher/blob/57bf7e79e785f71668ecdde08150c5b6b8657804/buildSrc/src/main/kotlin/Config.kt#L64

Since it's only a problem on that migration

**Comment by loosebazooka** [comment]
@tonyshkurenko can you provide a sample project to analyze this. Alternatively can you run 
```
$ ./gradlew buildEnvironment
```
to show the buildscript classpath.
