### PR TITLE
chore: update dependencies

### LINKED ISSUE #27: Applying Android Plugin fails on Gradle 6
With Gradle 6 building project fails with following message.
```
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.internal.application']
   > com.google.common.base.Suppliers$NonSerializableMemoizingSupplier cannot be cast to java.util.function.Supplier
```
This can be reproduced in fe: following repo https://github.com/Naitbit/ArtifactRegistryIssues

### LINKED ISSUE #44: Caused by: java.lang.NoClassDefFoundError: com/google/api/client/json/jackson2/JacksonFactory
Hi, I've got an exception, after updating AGP to 4.2.1, Gradle 6.7.1, artifactory plugin: 2.1.1

```
Caused by: java.lang.NoClassDefFoundError: com/google/api/client/json/jackson2/JacksonFactory
        at com.google.cloud.artifactregistry.auth.DefaultCredentialProvider.getCredential(DefaultCredentialProvider.java:49)
        at com.google.cloud.artifactregistry.gradle.plugin.ArtifactRegistryGradlePlugin.apply(ArtifactRegistryGradlePlugin.java:84)

```

### PR DESCRIPTION
**Pull request by yihanzhen**
Update google-http-client and google-auth-library-oauth2-http to the latest version.

Also explicitly depend on jackson2 becuase google-auth-library-oauth2-http stopped depending on jackson2 after 0.16.2 so we loose it as a transitive dependency.

Fix #27
Fix #44

### CODE REVIEW

**Comment by yihanzhen** [comment]
@loosebazooka the latest version of `google-auth-library-oauth2-http` is 1.0.0 which is a major version update from 0.16.2; want to run through you to see if this is fine. Thanks!

**Comment by chanseokoh** [comment]
For our project, we occasionally have issues when upgrading Google HTTP libraries and had to fix bugs in them or revert upgrading. And last week, it happened, and we decided to [downgrade them as there were issues](https://github.com/GoogleContainerTools/jib/issues/3416) one of which was critical. However, I *think* these issues only affect the Apache transport, which is what we [use](https://github.com/GoogleContainerTools/jib/blob/8a19850020eae077d6554f36d534fe2cdba37d6d/build.gradle#L61-L63) (with `google-http-client-apache-v2`).

We don't use `google-auth-library-oauth2-http` heavily in our code, so nothing to say about that. Just FYI, we went from `google-auth-library-oauth2-http:0.18.0` to `1.0.0` and then back to `0.18.0` after downgrading.

**Comment by yihanzhen** [comment]
@chanseokoh thanks!

> We don't use google-auth-library-oauth2-http heavily in our code, so nothing to say about that. Just FYI, we went from google-auth-library-oauth2-http:0.18.0 to 1.0.0 and then back to 0.18.0 after downgrading.

Is this because of something is off in `google-auth-library-oauth2-http`, or that is the version that works with the desired version of `google-http-client-apache-v2`?

**Comment by chanseokoh** [comment]
> Is this because of something is off in `google-auth-library-oauth2-http`, or that is the version that works with the desired version of `google-http-client-apache-v2`?

I have been just mechanically following the combination defined by the [`java-shared-dependencies` 2.0.1 BOM](https://github.com/googleapis/java-shared-dependencies/blob/8ed008c2a580785896c8e94a85a709c95ce75440/pom.xml#L66-L67) at that time, hoping for the best compatibility. Nothing else.

**Review by lindsayismith — APPROVED** [review]

**Comment by tonyshkurenko** [comment]
Hi, when do you plan to release this?

**Comment by yihanzhen** [comment]
@tonyshkurenko 2.1.3 is published!

**Comment by tonyshkurenko** [comment]
I'm not sure this PR changed something, but now this plugin relies on `artifactregistry-auth-common:2.1.3`, which is missing

```
A problem occurred configuring root project '***'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.google.cloud.artifactregistry:artifactregistry-auth-common:2.1.3.
   
   Required by:
         project : > gradle.plugin.com.google.cloud.artifactregistry:artifactregistry-gradle-plugin:2.1.3
```

I can find it here, but there is no `pom` file: https://repo1.maven.org/maven2/com/google/cloud/artifactregistry/artifactregistry-auth-common/2.1.3/

CC: @yihanzhen @lindsayismith @chanseokoh

**Comment by yihanzhen** [comment]
@tonyshkurenko not sure what happened. I just republished 2.1.4 and the pom file is there: https://repo.maven.apache.org/maven2/com/google/cloud/artifactregistry/artifactregistry-auth-common/2.1.4/
